name: "[QE] SonarCloud"

on:
  push:
    branches:
      - master
      - main
      - release/*
      - feature/*
      - fix/*
      - chore/*
  pull_request_target:
    branches:
    - master
    - main
    types:
    - labeled    

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ github.event_name == 'push' ||
            ( 
              github.event_name == 'pull_request_target' &&
              contains(github.event.label.name, 'safe to test')
            )
         }}      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Cache for node_modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          
      - name: Install base packages
        run: yarn install --frozen-lockfile
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        
      - name: Install react packages
        run: yarn install --frozen-lockfile
        working-directory: ./react
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          # SonarCloud doesn't treat pull_request_target, so we need this
          args: >
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} 
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} 
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
